image: Visual Studio 2017

platform:
    - x64

cache:
    - node_modules

install:
    # The x64 is required as a workaround for esy/esy#412
    - ps: Install-Product node 10 x64
    - npm install

build_script:
    - npm run build
    # Validate binary
    - lib\bs\native\gentype.native.exe --help
    - tar czvf gentype-win.tar.gz -C lib\bs\native gentype.native.exe

artifacts:
    - path: gentype-win.tar.gz
      name: Windows Build
      type: File

deploy:
    - provider: GitHub
      repository: cristianoc/genType
      auth_token:
        secure: Lqg37AH0Hg/rThuUMuQbzJbgYVCVlUV6RnAgFWb8gNcjNjPcMs46+JPTXNyqyQkQ
      draft: false
      artifact: gentype-win.tar.gz
      force_update: true
      on:
        appveyor_repo_tag: true