name: Build npm release

# Tag triggering:
# We build any tags starting prefixed with a `v`, based
# on the way npm tags version releases (e.g. v3.0.0)
#
# v2.* tags should only be recognized by our old CI systems
# (from branch 4_02), so we ignore everything starting with `v2.*`.
#
# Branch triggering:
# We configured only a set of static branches, which will be automatically
# built with every commit (even without PR).
#
# Branches with an open PR will automatically be built as well, so we don't
# have to list them here (otherwise we will have two CI builds every time)
trigger:
  tags:
    include:
      - v*
    exclude:
      - v2.*
  branches:
    include:
      - master
    exclude:
      - 4_02

pr:
  branches:
    include:
      - master
    exclude:
      - 4_02

jobs:
  - template: .ci/build-platform.yml
    parameters:
      platform: Linux
      vmImage: ubuntu-16.04
      STAGING_DIRECTORY: /home/vsts/STAGING

  - template: .ci/build-platform.yml
    parameters:
      platform: macOS
      vmImage: macOS-10.13
      STAGING_DIRECTORY: $(Build.StagingDirectory)

  - template: .ci/build-platform.yml
    parameters:
      platform: Windows
      vmImage: vs2017-win2016
      STAGING_DIRECTORY: C:\Users\VssAdministrator\STAGING

  # This job is kept here as we want to have the platform names in the same file
  - job: Release
    displayName: Release
    dependsOn:
      - Linux
      - macOS
      - Windows
    pool:
      vmImage: macOS-10.13
      demands: node.js
    steps:
      - template: .ci/cross-release.yml
