# We build artifacts to the `~/repo/dist` directory and attach it to the workspace
# so that the release jobs can access all the build artifacts of the workspace
# context.
#
# Therefore following mental directory model:
# ~/repo: the actual gentype repo
#  |- dist: contains all build artifacts
#  |- src
#  |- ...
#  |- package.json
#
# All commands should all be run in the workdir `~/repo` to prevent confusion.

version: 2
jobs:
  build_linux:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.11

    working_directory: ~/repo

    steps:
      - checkout 
      - attach_workspace:
          at: ~/repo/dist

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v0-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v0-dependencies-

      # build
      - run: npm install
      - run: npm run build

      - save_cache:
          key: v0-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # Tar things up
      - run: tar czvf dist/gentype-linux.tar.gz -C lib/bs/native gentype.native

      - store_artifacts:
          path: dist/gentype-linux.tar.gz
          destination: gentype-linux.tar.gz

      - persist_to_workspace:
          root: dist
          paths:
            - gentype-linux.tar.gz

  build_macos:
    macos:
      xcode: "9.0"

    working_directory: ~/repo

    steps:
      - checkout 

      - attach_workspace:
          at: ~/repo/dist

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v0-macos-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v0-macos-dependencies-

      # build
      - run: npm install
      - run: npm run build

      - save_cache:
          key: v0-macos-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # Tar things up
      - run: tar czvf dist/gentype-macos.tar.gz -C lib/bs/native gentype.native

      - store_artifacts:
          path: dist/gentype-macos.tar.gz
          destination: gentype-macos.tar.gz

      - persist_to_workspace:
          root: dist
          paths:
            - gentype-macos.tar.gz

  github_release:
    docker:
      - image: appropriate/curl:latest

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo/dist

      - run:
          name: Upload Linux binary
          command: .circleci/github_upload.sh dist/gentype-linux.tar.gz "gentype-linux-$CIRCLE_TAG.zip"
        
      - run:
          name: Upload MacOS binary
          command: .circleci/github_upload.sh dist/gentype-macos.tar.gz "gentype-macos-$CIRCLE_TAG.zip"

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_linux
      - build_macos
      - github_release:
        requires:
          - build_linux
          - build_macos
        filters:
          tags:
              only: /^v.*/
          branches:
              ignore: /.*/