name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-18.04, windows-latest]
        # syntax explanation:
        # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-additional-values-into-combinations
        include:
          - os: macos-latest
            build: eval $(opam env) && dune build && npm test
            artifact-folder: darwin
          - os: ubuntu-18.04
            build: eval $(opam env) && dune build && npm test
            artifact-folder: linux
          - os: windows-latest
            build: "& $env:CYGWIN_ROOT\\bin\\ocaml-env exec -- dune build"
            artifact-folder: win32

    runs-on: ${{matrix.os}}

    steps:
    # needed for Windows testing
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v2.3.4

    - name: Cache OCaml's opam
      uses: actions/cache@v2.1.5
      with:
        path: ~/.opam
        key: ${{matrix.os}}-rescript-vscode-v1

    - name: Use OCaml
      uses: ocaml/setup-ocaml@v1.1.11
      with:
        ocaml-version: 4.06.1

    - name: Use Node.js
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.4.0

    - run: npm ci

    - run: opam install dune

    - name: Build and test
      run: ${{matrix.build}}

    # Also avoids artifacts upload permission loss:
    # https://github.com/actions/upload-artifact/tree/ee69f02b3dfdecd58bb31b4d133da38ba6fe3700#permission-loss
    - name: Compress files
      run: |
        mkdir ${{matrix.artifact-folder}}
        cp _build/default/src/GenType.exe ${{matrix.artifact-folder}}/gentype.exe
        tar -cvf binary.tar ${{matrix.artifact-folder}}

    - uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.os}}
        path: binary.tar
